apiVersion: v1
kind: ServiceAccount
metadata:
  name: terraform
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: terraform-role
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["namespaces", "pods", "services", "deployments"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: terraform-role-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: terraform
    namespace: default
roleRef:
  kind: Role
  name: terraform-role
  apiGroup: rbac.authorization.k8s.io
